    /** @test */

    public function it_throws_not_found_exception_when_command_is_not_registered_in_container()
    {
        $botman = $this->getBot([
            'sender' => 'UX12345',
            'recipient' => 'general',
            'message' => 'Foo',
        ]);
        TestClass::$called = false;

        /** @var ContainerInterface|m\Mock $containerMock */
        $containerMock = m::mock(ContainerInterface::class);
        $exceptionMock = new class() extends \Exception implements NotFoundExceptionInterface {
        };
        $containerMock->shouldReceive('get')->once()->andThrow($exceptionMock);

        $botman->setContainer($containerMock);

        $botman->hears('foo', TestClass::class.'@foo');

        $this->expectException(NotFoundExceptionInterface::class);

        $botman->listen();
        $this->assertFalse(TestClass::$called);
    }
