    /**
     * Does the wrapped Exception has a previous Exception?
     * @return bool
     */

    public function hasPreviousException()
    {
        return $this->previousExceptionInspector || $this->exception->getPrevious();
    }
