    /**
     * @exepctedExceptionMessage Cannot reject a fulfilled promise
     */

    public function testCannotReject()
    {
        $this->expectException(\LogicException::class);

        $p = new FulfilledPromise('foo');
        $p->reject('bar');
    }
