    /**
     * @test
     */

    public function can_catch_failures_on_queue_export_job()
    {
        $export = new QueuedExportWithFailedEvents();

        try {
            $export->queue('queued-export.xlsx');
        } catch (Throwable $e) {
        }

        $this->assertTrue(app('queue-has-failed-from-queue-export-job'));
    }
