    /**
     * @test     The inverse of zero throws an exception.
     * @throws   \Exception
     */

    public function testInverseException()
    {
        // Given
        $number = new Rational(0, 0, 1);

        // Then
        $this->expectException(Exception\DivisionByZeroException::class);

        // When
        $number->inverse();
    }
